# Generated by Django 5.0.6 on 2024-06-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileimg',
            new_name='image',
        ),
    ]
