# Generated by Django 5.0.6 on 2024-06-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_profileimg_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
